<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <MicrosoftNoTargetsSdkImported Condition="'$(UsingMicrosoftNoTargetsSdk)' != 'true'">true</MicrosoftNoTargetsSdkImported>
  </PropertyGroup>

  <Import Condition="'$(UsingMicrosoftNoTargetsSdk)' != 'true'" Sdk="Microsoft.Build.NoTargets" Version="3.0.4" Project="sdk.props"/>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>

    <Win32MetadataSdkRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..'))</Win32MetadataSdkRoot>
    <Win32MetadataToolsDir Condition="'$(Win32MetadataToolsDir)' == ''">$(Win32MetadataSdkRoot)\tools\win-x64</Win32MetadataToolsDir>
    <Win32MetadataToolsExe Condition="'$(Win32MetadataToolsExe)' == ''">$(Win32MetadataToolsDir)\win32metadata-tools.exe</Win32MetadataToolsExe>
    <LibClangPath Condition="'$(LibClangPath)' == ''">$(Win32MetadataToolsDir)</LibClangPath>

    <ObjDir Condition="'$(ObjDir)' == ''">$(MSBuildProjectDirectory)\obj</ObjDir>
    <WinmdObjDir Condition="'$(WinmdObjDir)' == ''">$(ObjDir)\winmd</WinmdObjDir>
    <OutputWinmd Condition="'$(OutputWinmd)' == ''">$(MSBuildProjectDirectory)\bin\$(MSBuildProjectName).winmd</OutputWinmd>
    <TargetArchitectures Condition="'$(TargetArchitectures)' == ''">x64;x86;arm64</TargetArchitectures>
    <WinmdRootNamespace Condition="'$(WinmdRootNamespace)' == ''">Windows.Win32</WinmdRootNamespace>
    <WinmdAssemblyName Condition="'$(WinmdAssemblyName)' == ''">$([System.IO.Path]::GetFileNameWithoutExtension('$(OutputWinmd)'))</WinmdAssemblyName>

    <Win32MetadataAssetsDir Condition="'$(Win32MetadataAssetsDir)' == ''">$(Win32MetadataSdkRoot)\tools\assets</Win32MetadataAssetsDir>
    <WinSDKAssets Condition="'$(WinSDKAssets)' == ''">$(Win32MetadataAssetsDir)\WinSDK</WinSDKAssets>
    <SdkIncRoot Condition="'$(SdkIncRoot)' == ''">$(TargetPlatformSdkRootOverride)\include\$(TargetPlatformVersion)</SdkIncRoot>
    <UseWinSDKAssets Condition="'$(UseWinSDKAssets)' == ''">true</UseWinSDKAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.CPP" Version="10.0.19041.5" GeneratePathProperty="true"/>
  </ItemGroup>
</Project>
