version: 2
registries:
  nuget-azure-devops:
    type: nuget-feed
    # The URL of the NuGet feed to check for updates
    url: https://pkgs.dev.azure.com/shine-oss/Win32Metadata/_packaging/Win32Metadata-Dependencies/nuget/v3/index.json
updates:
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the `root` directory
    directory: "/"
    # Check the nuget registry for updates monthly
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with "dependbot-security-updates: "
      prefix: "dependbot-security-updates"
    registries:
      - nuget-azure-devops
    groups:
      nuget-dependencies:
        dependency-type: production
        applies-to: security-updates