using System;

namespace Windows.Win32.Storage.Xps
{
    [Flags]
    public enum PSINJECT_POINT : ushort
    {
        PSINJECT_BEGINSTREAM = 1,
        PSINJECT_PSADOBE = 2,
        PSINJECT_PAGESATEND = 3,
        PSINJECT_PAGES = 4,
        PSINJECT_DOCNEEDEDRES = 5,
        PSINJECT_DOCSUPPLIEDRES = 6,
        PSINJECT_PAGEORDER = 7,
        PSINJECT_ORIENTATION = 8,
        PSINJECT_BOUNDINGBOX = 9,
        PSINJECT_DOCUMENTPROCESSCOLORS = 10,
        PSINJECT_COMMENTS = 11,
        PSINJECT_BEGINDEFAULTS = 12,
        PSINJECT_ENDDEFAULTS = 13,
        PSINJECT_BEGINPROLOG = 14,
        PSINJECT_ENDPROLOG = 15,
        PSINJECT_BEGINSETUP = 16,
        PSINJECT_ENDSETUP = 17,
        PSINJECT_TRAILER = 18,
        PSINJECT_EOF = 19,
        PSINJECT_ENDSTREAM = 20,
        PSINJECT_DOCUMENTPROCESSCOLORSATEND = 21,
        PSINJECT_PAGENUMBER = 100,
        PSINJECT_BEGINPAGESETUP = 101,
        PSINJECT_ENDPAGESETUP = 102,
        PSINJECT_PAGETRAILER = 103,
        PSINJECT_PLATECOLOR = 104,
        PSINJECT_SHOWPAGE = 105,
        PSINJECT_PAGEBBOX = 106,
        PSINJECT_ENDPAGECOMMENTS = 107,
        PSINJECT_VMSAVE = 200,
        PSINJECT_VMRESTORE = 201
    }
}
