#define WIN32_LEAN_AND_MEAN

#include <windows.h>

#undef GetUserName
#undef GetClassInfo
#undef GetMessage
#undef GetJob
#undef GetLocaleInfo
#undef GetDiskSpaceInformation
#undef GetUserNameEx
#undef GetComputerObjectName
#undef TranslateName
#undef GetFileAttributes
#undef GetTimeFormat
#undef GetClassName
#undef GetGlyphIndices

#undef LoadKeyboardLayout
#undef GetKeyboardLayoutName
#undef DispatchMessage
#undef PeekMessage
#undef SendMessage
#undef RegisterClass
#undef UnregisterClass
#undef CreateDialog
#undef DialogBox
#undef LoadMenu
#undef ChangeMenu
#undef SetProp
#undef GetProp
#undef GetMenuString
#undef InsertMenu
#undef AppendMenu
#undef ModifyMenu
#undef InsertMenuItem
#undef DrawText
#undef DrawState
#undef RemoveProp
#undef EnumProps
#undef MessageBox
#undef FindWindow
#undef LoadBitmap
#undef LoadCursor
#undef LoadIcon
#undef LoadImage
#undef LoadString
#undef WinHelp
#undef ChangeDisplaySettings
#undef ChangeDisplaySettingsEx
#undef EnumDisplaySettings
#undef EnumDisplaySettingsEx
#undef EnumDisplayDevices
#undef GetMonitorInfo
#undef SetLocaleInfo
#undef SetEnvironmentVariable
#undef SetPort
#undef StartService
#undef ReportEvent
#undef TranslateAccelerator
#undef CreateDirectory
#undef DeleteFile

#include <combaseapi.h>
