namespace Windows.Win32.Media.MediaPlayer
{
    public static partial class Apis
    {
        public const uint DISPID_WMPCONTROLS_BASE = DISPID_WMPCORE_BASE + DISPID_DELTA;

        public const uint DISPID_WMPSETTINGS_BASE = DISPID_WMPCONTROLS_BASE + DISPID_DELTA;

        public const uint DISPID_WMPPLAYLIST_BASE = DISPID_WMPSETTINGS_BASE + DISPID_DELTA + DISPID_DELTA;

        public const uint DISPID_WMPCDROM_BASE = DISPID_WMPPLAYLIST_BASE + DISPID_DELTA;

        public const uint DISPID_WMPCDROMCOLLECTION_BASE = DISPID_WMPCDROM_BASE + DISPID_DELTA;

        public const uint DISPID_WMPSTRINGCOLLECTION_BASE = (DISPID_WMPCDROMCOLLECTION_BASE + DISPID_DELTA + DISPID_DELTA);

        public const uint DISPID_WMPMEDIACOLLECTION_BASE = DISPID_WMPSTRINGCOLLECTION_BASE + DISPID_DELTA;

        public const uint DISPID_WMPPLAYLISTARRAY_BASE = DISPID_WMPMEDIACOLLECTION_BASE + DISPID_DELTA;
         
        public const uint DISPID_WMPPLAYLISTCOLLECTION_BASE = DISPID_WMPPLAYLISTARRAY_BASE + DISPID_DELTA;

        public const uint DISPID_WMPMEDIA_BASE = (DISPID_WMPPLAYLISTCOLLECTION_BASE + (4 * DISPID_DELTA));

        public const uint DISPID_WMPNETWORK_BASE = DISPID_WMPMEDIA_BASE + DISPID_DELTA;

        public const uint DISPID_WMPERROR_BASE = DISPID_WMPNETWORK_BASE + DISPID_DELTA;

        public const uint DISPID_WMPERRORITEM_BASE = DISPID_WMPERROR_BASE + DISPID_DELTA;

        public const uint DISPID_WMPCLOSEDCAPTION_BASE = DISPID_WMPERRORITEM_BASE + DISPID_DELTA;

        public const uint DISPID_WMPDVD_BASE = DISPID_WMPCLOSEDCAPTION_BASE + DISPID_DELTA;

        public const uint DISPID_WMPMETADATA_BASE = DISPID_WMPDVD_BASE + DISPID_DELTA;

        public const uint DISPID_WMPPLAYERAPP_BASE = DISPID_WMPMETADATA_BASE + DISPID_DELTA;

        public const uint DISPID_WMPDOWNLOADMANAGER_BASE = DISPID_WMPPLAYERAPP_BASE + DISPID_DELTA;

        public const uint DISPID_WMPDOWNLOADCOLLECTION_BASE = DISPID_WMPDOWNLOADMANAGER_BASE + DISPID_DELTA;

        public const uint DISPID_WMPDOWNLOADITEM_BASE = DISPID_WMPDOWNLOADCOLLECTION_BASE + DISPID_DELTA;

        public const uint DISPID_WMPDOWNLOADITEM2_BASE = DISPID_WMPDOWNLOADITEM_BASE + DISPID_DELTA;

        public const uint DISPID_WMPQUERY_BASE = DISPID_WMPDOWNLOADITEM2_BASE + DISPID_DELTA;

        public const uint DISPID_WMPMEDIACOLLECTION2_BASE = DISPID_WMPQUERY_BASE + DISPID_DELTA;

        public const uint DISPID_WMPSTRINGCOLLECTION2_BASE = DISPID_WMPMEDIACOLLECTION2_BASE + DISPID_DELTA;
    }
}
