# ApplySDKPatches.ps1
# Applies SDK header patches from generation/WinSDK/patches/{phase}/ directories.
#
# Patches are unified diffs (generated by `git diff`) with paths relative to the repo root.
# They are organized by phase:
#   patches/pre-midl/   — Applied after SDK copy, before MIDL recompilation.
#                         Use for .idl files and headers included during MIDL compilation.
#   patches/post-midl/  — Applied after MIDL recompilation and header restores.
#                         Use for .h files not generated by MIDL, or direct header patches.
#
# Creating a new patch:
#   1. Run UpdateSDK.ps1 (or RecompileIdlFilesForScraping.ps1) to get a pristine SDK copy
#   2. Edit the target file in RecompiledIdlHeaders/
#   3. From the repo root, run:
#        git diff -- "generation/WinSDK/RecompiledIdlHeaders/um/<file>" > "generation/WinSDK/patches/<phase>/<file>.patch"
#   4. The patched file in RecompiledIdlHeaders/ stays as-is (it's the committed result)
#
# IMPORTANT: When updating an existing patch after an SDK update, the fresh SDK copy is already
# the correct baseline. Edit the file, re-run `git diff`, and overwrite the patch file.
#
# Usage:
#   . .\ApplySDKPatches.ps1 -Phase pre-midl     # Apply pre-MIDL patches (IDL files, etc.)
#   . .\ApplySDKPatches.ps1 -Phase post-midl    # Apply post-MIDL patches (header files)

[CmdletBinding()]
Param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("pre-midl", "post-midl")]
    [string]$Phase
)

. "$PSScriptRoot\CommonUtils.ps1"

$patchDir = Join-Path $windowsWin32ProjectRoot "patches\$Phase"

if (!(Test-Path $patchDir)) {
    Write-Host "No $Phase patches directory found. Skipping."
    return
}

$patchFiles = Get-ChildItem -Path $patchDir -Filter "*.patch" -Recurse | Sort-Object FullName
if ($patchFiles.Count -eq 0) {
    Write-Host "No $Phase patch files found. Skipping."
    return
}

$appliedCount = 0
$failedCount = 0

foreach ($patchFile in $patchFiles) {
    $relativeName = $patchFile.FullName.Substring($patchDir.Length + 1)
    Write-Host "Applying $Phase patch: $relativeName..."

    # Anchor git to repo root so patch paths (generation/WinSDK/...) resolve correctly
    git -C $rootDir apply $patchFile.FullName 2>&1 | ForEach-Object { Write-Host "  $_" }
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  Applied successfully" -ForegroundColor Green
        $appliedCount++
    } else {
        Write-Warning "  FAILED to apply patch: $relativeName"
        Write-Warning "  The SDK headers may have changed. Regenerate this patch against the new SDK."
        $failedCount++
    }
}

Write-Host "SDK $Phase patches: $appliedCount applied, $failedCount failed (of $($patchFiles.Count))."

if ($failedCount -gt 0) {
    Write-Error "$Phase patches failed. Regenerate failing patches against the new SDK headers."
    exit 1
}
