// Header and import-library orchestration copied from jevansaks/windows-rs
// d08dd0c613bb13c0bf6d7e206fd9abdb818824ff.

pub const EXCLUDE_HEADERS: &[&str] = &[
    "basetyps.h",
    "driverspecs.h",
    "intsafe.h",
    "rpcsal.h",
    "specstrings.h",
    "specstrings_strict.h",
];

pub const HEADERS: &[&str] = &[
    "shellscalingapi.h",
    "tlhelp32.h",
    "wingdi.h",
    "winuser.h",
    "commctrl.h",
    "setupapi.h",
    "winhttp.h",
    "wininet.h",
    "objidl.h",
    "oaidl.h",
    "ocidl.h",
    "wincrypt.h",
    "d2d1.h",
    "d3d11.h",
    "d3d11shadertracing.h",
    "dwrite.h",
    "wincodec.h",
    "d3d12.h",
    "dxgi1_6.h",
    "shobjidl.h",
    "shlobj.h",
    "shellapi.h",
    "shlwapi.h",
    "pathcch.h",
    "mfapi.h",
    "mfidl.h",
    "mfreadwrite.h",
    "mftransform.h",
    "mmdeviceapi.h",
    "audioclient.h",
    "xaudio2.h",
    "dsound.h",
    "dshow.h",
    "dcomp.h",
    "DispatcherQueue.h",
    "dwrite_3.h",
    "d2d1_3.h",
    "d3d9.h",
    "d3d10.h",
    "cfgmgr32.h",
    "bluetoothapis.h",
    "hidsdi.h",
    "wintrust.h",
    "authz.h",
    "http.h",
    "wbemcli.h",
    "wbemidl.h",
    "netioapi.h",
    "ifdef.h",
    "ws2bth.h",
    "mswsock.h",
    "sspi.h",
    "schannel.h",
    "ntsecapi.h",
    "ntsecpkg.h",
    "propsys.h",
    "propvarutil.h",
    "dwmapi.h",
    "uxtheme.h",
    "wlanapi.h",
    "dxva2api.h",
    "wincodecsdk.h",
    "d3d11_4.h",
    "dxgidebug.h",
    "powrprof.h",
    "newdev.h",
    "bthledef.h",
    "winioctl.h",
    "devpkey.h",
    "knownfolders.h",
    "propkey.h",
    "spellcheck.h",
    "usp10.h",
    "dxcore.h",
    "d3d11on12.h",
    "d3d12video.h",
    "netlistmgr.h",
    "netfw.h",
    "wincred.h",
    "wtsapi32.h",
    "tsvirtualchannels.h",
    "evntrace.h",
    "tdh.h",
    "powersetting.h",
    "ws2tcpip.h",
    "afunix.h",
    "userenv.h",
    "iphlpapi.h",
    "fileapi.h",
    "processthreadsapi.h",
    "sysinfoapi.h",
    "memoryapi.h",
    "ntenclv.h",
    "psapi.h",
    "winreg.h",
    "winsvc.h",
    "bcrypt.h",
    "ncrypt.h",
    "winnls.h",
    "winspool.h",
    "winnetwk.h",
    "windns.h",
    "mmsystem.h",
    "timeapi.h",
    "joystickapi.h",
    "mmeapi.h",
    "pdh.h",
    "usbioctl.h",
    "virtdisk.h",
    "werapi.h",
    "expandedresources.h",
    "d3dcompiler.h",
    "sensorsapi.h",
    "rpcdce.h",
    "avrt.h",
    "winbio.h",
    "cryptuiapi.h",
    "certenroll.h",
    "portabledeviceapi.h",
    "taskschd.h",
    "wuapi.h",
    "dbghelp.h",
    "DbgProp.h",
    "evr.h",
    "codecapi.h",
    "directml.h",
    "sapi.h",
    "sapiddk.h",
    "wcmapi.h",
    "uiautomationcore.h",
    "uiautomationclient.h",
    "oleacc.h",
    "msctf.h",
    "textstor.h",
    "tom.h",
    "richedit.h",
    "fwpmu.h",
    "icmpapi.h",
    "mstcpip.h",
    "wsrm.h",
    "mfmediaengine.h",
    "wmcodecdsp.h",
    "exdisp.h",
    "msi.h",
    "msiquery.h",
    "xmllite.h",
    "aclapi.h",
    "sddl.h",
    "winsafer.h",
    "dsgetdc.h",
    "comcat.h",
    "winevt.h",
    "ktmw32.h",
    "clusapi.h",
    "dhcpsapi.h",
    "ntdsapi.h",
    "dsrole.h",
    "magnification.h",
    "winusb.h",
    "directmanipulation.h",
    "xinput.h",
    "restartmanager.h",
    "compressapi.h",
    "patchapi.h",
    "searchapi.h",
    "structuredquery.h",
    "fltuser.h",
    "wsdapi.h",
    "functiondiscoveryapi.h",
    "wia.h",
    "prntvpt.h",
    "dinput.h",
    "vss.h",
    "vswriter.h",
    "vsbackup.h",
    "iads.h",
    "adshlp.h",
    "gpedit.h",
    "locationapi.h",
    "mscat.h",
    "mssip.h",
    "imapi2.h",
    "wscapi.h",
    "sensapi.h",
    "rtworkq.h",
    "icm.h",
    "dmoreg.h",
    "dmort.h",
    "uianimation.h",
    "urlmon.h",
    "xpsprint.h",
    "xpsobjectmodel.h",
    "msinkaut.h",
    "amsi.h",
    "comadmin.h",
    "comsvcs.h",
    "cryptxml.h",
    "winldap.h",
    "mq.h",
    "winhvplatform.h",
    "websocket.h",
    "ras.h",
    "rasdlg.h",
    "mprapi.h",
    "qos2.h",
    "d3dkmthk.h",
    "winscard.h",
    "dpapi.h",
    "ncryptprotect.h",
    "secext.h",
    "ntddscsi.h",
    "slpublic.h",
    "t2embapi.h",
    "traffic.h",
    "wsmandisp.h",
    "vfw.h",
    "dbgeng.h",
    "msxml6.h",
    "bits.h",
    "mlang.h",
    "wpcapi.h",
    "mfplay.h",
    "wmsdk.h",
    "ks.h",
    "ksmedia.h",
    "bdaiface.h",
    "tuner.h",
    "d3dkmdt.h",
    "dxgicommon.h",
    "ntddndis.h",
    "ntddvol.h",
    "ntddmmc.h",
    "usbspec.h",
    "hidpi.h",
    "vhf.h",
    "webauthn.h",
    "appxpackaging.h",
    "appmodel.h",
    "fsrm.h",
    "fsrmpipeline.h",
    "pla.h",
    "gameux.h",
    "msdrm.h",
    "certadm.h",
    "certsrv.h",
    "mfcaptureengine.h",
    "credentialprovider.h",
    "shdeprecated.h",
    "shdispid.h",
    "peninputpanel.h",
    "sti.h",
    "imapi2fs.h",
    "wmiutils.h",
    "txfw32.h",
    "fhcfg.h",
    "mferror.h",
    "msctfmonitorapi.h",
    "audioclientactivationparams.h",
    "spatialaudiometadata.h",
    "spatialaudioclient.h",
    "ntstatus.h",
    "sql.h",
    "sqlext.h",
    "esent.h",
    "vds.h",
    "regstr.h",
    "nvme.h",
    "ExDispid.h",
    "msxml6did.h",
    "wmp.h",
    "wmpids.h",
    "gl/gl.h",
    "webservices.h",
    "icu.h",
    "lmaccess.h",
    "lmshare.h",
    "lmserver.h",
    "lmwksta.h",
    "lmuse.h",
    "richole.h",
    "textserv.h",
    "commoncontrols.h",
    "dlgs.h",
    "mfobjects.h",
    "ntquery.h",
    "compstui.h",
    "mfvirtualcamera.h",
    "mfcontentdecryptionmodule.h",
    "mfd3d12.h",
    "mfspatialaudio.h",
    "portabledevice.h",
    "wdbgexts.h",
    "lmat.h",
    "lmconfig.h",
    "lmstats.h",
    "lmsvc.h",
    "lmmsg.h",
    "lmremutl.h",
    "lmrepl.h",
    "lmalert.h",
    "lmjoin.h",
    "filter.h",
    "httpext.h",
    "httpfilt.h",
    "iiscnfg.h",
    "IntShCut.h",
    "cfapi.h",
    "wct.h",
    "Windows.Devices.Display.Core.Interop.h",
    // WinRT interop factory/native bridge headers (`um\` dir). These are the MIDL-generated
    // C-ABI interop headers whose `HWND`/`REFIID`/`void**` (or DXGI/D2D) bridge interfaces
    // win32metadata mapped to `Windows.Win32.System.WinRT[.*]`. They include only light COM
    // headers (`windows.h`, `ole2.h`, `oaidl.h`, `inspectable.h`, `dxgi.h`, ...) already in the
    // main TU - *not* the C++/WinRT projection headers (`windows.*.h`) - so they parse cleanly;
    // any WinRT type they reach is resolved via the resolution winmd (see [`RESOLUTION_WINMDS`]).
    "UserConsentVerifierInterop.h",
    "UIViewSettingsInterop.h",
    "inputpaneinterop.h",
    "accountssettingspaneinterop.h",
    "dragdropinterop.h",
    "PrintManagerInterop.h",
    "Print3DManagerInterop.h",
    "PlayToManagerInterop.h",
    "SystemMediaTransportControlsInterop.h",
    "SpatialInteractionManagerInterop.h",
    "HolographicSpaceInterop.h",
    "WebAuthenticationCoreManagerInterop.h",
    "useractivityinterop.h",
    "sharewindowcommandsourceinterop.h",
    "appserviceinterop.h",
    "CastingInterop.h",
    "RadialControllerInterop.h",
    "RemoteSystemsInterop.h",
    "windows.security.isolation.isolatedenvironmentinterop.h",
    "windows.ui.viewmanagement.core.coreframeworkinputviewinterop.h",
    "windows.graphics.directx.direct3d11.interop.h",
    "windows.graphics.display.interop.h",
    "windows.graphics.imaging.interop.h",
    "windows.media.core.interop.h",
    "windows.data.pdf.interop.h",
    "windows.ui.xaml.media.dxinterop.h",
    "windows.ui.xaml.hosting.desktopwindowxamlsource.h",
    "windows.ui.xaml.hosting.referencetracker.h",
    // XAML diagnostics has no SDK import library. Its exported entry point is mapped by
    // `LIBRARY_OVERRIDES`.
    "xamlOM.h",
    "WindowsStorageCOM.h",
    // Interop headers that `#include` a `winrt\` C++/WinRT projection header whose transitive
    // closure fails to parse; the scraper tolerates errors in those out-of-scope projection
    // headers and scrapes only the trivial interop interfaces from these in-scope headers
    // (capture names no projected type; composition names a few
    // `ABI::Windows::UI::Composition::*` interfaces resolved via the resolution winmd).
    "Windows.Graphics.Capture.Interop.h",
    "windows.ui.composition.interop.h",
    // WinRT C-ABI interop (winrt\ dir, out of the um/shared scope but named here so
    // scope_headers makes them roots). These are the flat COM/C interop headers that
    // win32metadata maps to Windows.Win32.System.WinRT[.Metadata] - NOT the winmd-generated
    // C++ projection (windows.*.h) nor the C++ template libraries (wrl.h / WinRTBase.h /
    // cppwinrt\), which stay excluded.
    "roerrorapi.h",
    "activation.h",
    "corewindow.h",
    "hstring.h",
    "inspectable.h",
    "memorybuffer.h",
    "roapi.h",
    "robuffer.h",
    "roregistrationapi.h",
    "shcore.h",
    "weakreference.h",
    "winstring.h",
    "rometadata.h",
    "roparameterizediid.h",
    "audiopolicy.h",
    // Excluded WinRT interop headers: `RoMetadataApi.h` and `rometadataresolution.h`
    // `#include <cor.h>`, the CLR unmanaged-metadata header, which ships only in the
    // NETFXSDK (not the pinned Windows SDK NuGet) - pulling it in would make the scrape
    // depend on a non-pinned, system-autodetected header and break the hermetic CI build.
    // `RoMetadataApi.h`'s `IMetaData*` reader interfaces are low-value CLR plumbing, so the
    // header is dropped rather than dragging in the .NET metadata surface. `roregistrationapi.h`
    // *is* scraped: its closure references the `ABI::Windows::Foundation` projection namespace,
    // whose Win32 COM interop entities (`IActivatableClassRegistration` and its enums) are
    // reached via the resolution winmd (see [`RESOLUTION_WINMDS`]).
];

pub const SATELLITE_HEADERS: &[&str] = &[
    "ntddstor.h",
    "ntddcdrm.h",
    "ntddtape.h",
    "ntddser.h",
    "ntddkbd.h",
    "ntddmou.h",
    "usbiodef.h",
    "poclass.h",
    "batclass.h",
    "hidclass.h",
    "winternl.h",
    "endpointvolume.h",
    "devicetopology.h",
];

/// Curated SDK imports, retaining upstream order. Symbol routing is first-wins.
pub const IMPORT_LIBS: &[&str] = &[
    "shcore.lib",
    "kernel32.lib",
    "gdi32.lib",
    "gdiplus.lib",
    "user32.lib",
    "msimg32.lib",
    "opengl32.lib",
    "glu32.lib",
    "lz32.lib",
    "advapi32.lib",
    "ole32.lib",
    "oleaut32.lib",
    "runtimeobject.lib",
    "crypt32.lib",
    "rpcrt4.lib",
    "winmm.lib",
    "shell32.lib",
    "comdlg32.lib",
    "urlmon.lib",
    "winspool.lib",
    "winscard.lib",
    "cldapi.lib",
    "ws2_32.lib",
    "version.lib",
    "secur32.lib",
    "mpr.lib",
    "ntdll.lib",
    "userenv.lib",
    "imm32.lib",
    "bcrypt.lib",
    "ncrypt.lib",
    "rpcns4.lib",
    "comctl32.lib",
    "setupapi.lib",
    "winhttp.lib",
    "wininet.lib",
    "iphlpapi.lib",
    "d3d12.lib",
    "d3d11.lib",
    "d2d1.lib",
    "dwrite.lib",
    "dxgi.lib",
    "shlwapi.lib",
    "mfplat.lib",
    "mf.lib",
    "mfreadwrite.lib",
    "dsound.lib",
    "dcomp.lib",
    "CoreMessaging.lib",
    "d3d9.lib",
    "d3d10.lib",
    "cfgmgr32.lib",
    "bthprops.lib",
    "hid.lib",
    "wintrust.lib",
    "authz.lib",
    "httpapi.lib",
    "mswsock.lib",
    "wlanapi.lib",
    "dwmapi.lib",
    "uxtheme.lib",
    "propsys.lib",
    "powrprof.lib",
    "newdev.lib",
    "dxva2.lib",
    "dxcore.lib",
    "wtsapi32.lib",
    "tdh.lib",
    "dnsapi.lib",
    "pdh.lib",
    "virtdisk.lib",
    "wer.lib",
    "d3dcompiler.lib",
    "sensorsapi.lib",
    "avrt.lib",
    "winbio.lib",
    "cryptui.lib",
    "dbghelp.lib",
    "mfuuid.lib",
    "sapi.lib",
    "portabledeviceguids.lib",
    "uiautomationcore.lib",
    "oleacc.lib",
    "fwpuclnt.lib",
    "msi.lib",
    "netapi32.lib",
    "xmllite.lib",
    "wevtapi.lib",
    "ktmw32.lib",
    "clusapi.lib",
    "dhcpsapi.lib",
    "ntdsapi.lib",
    "magnification.lib",
    "winusb.lib",
    "xinput.lib",
    "rstrtmgr.lib",
    "cabinet.lib",
    "mspatchc.lib",
    "fltlib.lib",
    "prntvpt.lib",
    "wiaguid.lib",
    "dinput8.lib",
    "vssapi.lib",
    "activeds.lib",
    "adsiid.lib",
    "wscapi.lib",
    "sensapi.lib",
    "rtworkq.lib",
    "mscms.lib",
    "msdmo.lib",
    "dmoguids.lib",
    "xpsprint.lib",
    "amsi.lib",
    "cryptxml.lib",
    "wldap32.lib",
    "mqrt.lib",
    "winhvplatform.lib",
    "websocket.lib",
    "rasapi32.lib",
    "rasdlg.lib",
    "mprapi.lib",
    "qwave.lib",
    "slc.lib",
    "slwga.lib",
    "t2embed.lib",
    "traffic.lib",
    "wsmsvc.lib",
    "vfw32.lib",
    "dbgeng.lib",
    "msxml6.lib",
    "bits.lib",
    "wmvcore.lib",
    "ksuser.lib",
    "webauthn.lib",
    "msdrm.lib",
    "certadm.lib",
    "sti.lib",
    "txfw32.lib",
    "mfsensorgroup.lib",
    "icuuc.lib",
    "icuin.lib",
    "esent.lib",
    "webservices.lib",
    "odbc32.lib",
    "icu.lib",
    "clfsw32.lib",
    "msacm32.lib",
    "usp10.lib",
    "wsdapi.lib",
    "hlink.lib",
    "icm32.lib",
    "credui.lib",
    "mspatcha.lib",
    "schannel.lib",
    "comsvcs.lib",
    "gpedit.lib",
    "scarddlg.lib",
    "cryptnet.lib",
    "wcmapi.lib",
    "rpcproxy.lib",
    "slcext.lib",
    "compstui.lib",
    "query.lib",
    "msctfmonitor.lib",
    "shdocvw.lib",
    "icmui.lib",
    "normaliz.lib",
    "dflayout.lib",
    "wlanui.lib",
    "mmdevapi.lib",
    "ddraw.lib",
    "evr.lib",
    "d3d10_1.lib",
    "mfcore.lib",
    "mfsrcsnk.lib",
    "quartz.lib",
    "mfplay.lib",
    "onecore.lib",
    "onecoreuap.lib",
    "vertdll.lib",
];

/// Dedicated SDK import archives required by additional traversed partitions.
/// Append after IMPORT_LIBS so existing first-wins symbol routing is unchanged.
pub const PARTITION_IMPORT_LIBS: &[&str] = &[
    "advpack.lib",
    "bcp47mrm.lib",
    "bindlink.lib",
    "bluetoothapis.lib",
    "certpoleng.lib",
    "computecore.lib",
    "computenetwork.lib",
    "computestorage.lib",
    "cscapi.lib",
    "dbgmodel.lib",
    "dciman32.lib",
    "dmprocessxmlfiltered.lib",
    "dsprop.lib",
    "eappcfg.lib",
    "eappprxy.lib",
    "efswrt.lib",
    "elscore.lib",
    "faultrep.lib",
    "fhsvcctl.lib",
    "fxsutility.lib",
    "imagehlp.lib",
    "imgutil.lib",
    "infocardapi.lib",
    "iscsidsc.lib",
    "isolatedwindowsenvironmentutils.lib",
    "keycredmgr.lib",
    "ksproxy.lib",
    "licenseprotection.lib",
    "loadperf.lib",
    "mdmlocalmanagement.lib",
    "mdmregistration.lib",
    "mgmtapi.lib",
    "mrmsupport.lib",
    "msdelta.lib",
    "msports.lib",
    "msrating.lib",
    "mstask.lib",
    "mtxdm.lib",
    "ndfapi.lib",
    "ninput.lib",
    "ondemandconnroutehelper.lib",
    "peerdist.lib",
    "projectedfslib.lib",
    "resutils.lib",
    "rtutils.lib",
    "sas.lib",
    "sensorsutils.lib",
    "sfc.lib",
    "snmpapi.lib",
    "spoolss.lib",
    "srpapi.lib",
    "tapi32.lib",
    "tbs.lib",
    "ualapi.lib",
    "umpdddi.lib",
    "vmdevicehost.lib",
    "vmsavedstatedumpprovider.lib",
    "wdsbp.lib",
    "wdsclientapi.lib",
    "wdstptc.lib",
    "wecapi.lib",
    "windows.media.mediacontrol.lib",
    "winfax.lib",
    "winhvemulation.lib",
    "winml.lib",
    "wnvapi.lib",
    "wofutil.lib",
];

pub struct LibraryOverride {
    pub symbol: &'static str,
    pub sdk_library: Option<&'static str>,
    pub corrected_library: &'static str,
}

/// Corrections for known defects in the pinned SDK import-library data.
pub const LIBRARY_OVERRIDES: &[LibraryOverride] = &[
    LibraryOverride {
        symbol: "DecodeRemotePointer",
        sdk_library: Some("api-ms-win-core-util-l1-1-1.dll"),
        corrected_library: "KernelBase.dll",
    },
    LibraryOverride {
        symbol: "EncodeRemotePointer",
        sdk_library: Some("api-ms-win-core-util-l1-1-1.dll"),
        corrected_library: "KernelBase.dll",
    },
    LibraryOverride {
        symbol: "OpenTraceFromBufferStream",
        sdk_library: Some("ADVAPI32.dll"),
        corrected_library: "api-ms-win-eventing-consumer-l1-1-2.dll",
    },
    LibraryOverride {
        symbol: "OpenTraceFromFile",
        sdk_library: Some("ADVAPI32.dll"),
        corrected_library: "api-ms-win-eventing-consumer-l1-1-2.dll",
    },
    LibraryOverride {
        symbol: "OpenTraceFromRealTimeLogger",
        sdk_library: Some("ADVAPI32.dll"),
        corrected_library: "api-ms-win-eventing-consumer-l1-1-2.dll",
    },
    LibraryOverride {
        symbol: "OpenTraceFromRealTimeLoggerWithAllocationOptions",
        sdk_library: Some("ADVAPI32.dll"),
        corrected_library: "api-ms-win-eventing-consumer-l1-1-2.dll",
    },
    LibraryOverride {
        symbol: "ProcessTraceAddBufferToBufferStream",
        sdk_library: Some("ADVAPI32.dll"),
        corrected_library: "api-ms-win-eventing-consumer-l1-1-2.dll",
    },
    LibraryOverride {
        symbol: "ProcessTraceBufferDecrementReference",
        sdk_library: Some("ADVAPI32.dll"),
        corrected_library: "api-ms-win-eventing-consumer-l1-1-2.dll",
    },
    LibraryOverride {
        symbol: "ProcessTraceBufferIncrementReference",
        sdk_library: Some("ADVAPI32.dll"),
        corrected_library: "api-ms-win-eventing-consumer-l1-1-2.dll",
    },
    LibraryOverride {
        symbol: "TraceConfigureLastBranchRecord",
        sdk_library: Some("ADVAPI32.dll"),
        corrected_library: "api-ms-win-eventing-consumer-l1-1-2.dll",
    },
    LibraryOverride {
        symbol: "GetRuntimeAttestationReport",
        sdk_library: Some("KERNEL32.dll"),
        corrected_library: "KernelBase.dll",
    },
    LibraryOverride {
        symbol: "GetSystemLeapSecondInformation",
        sdk_library: Some("KERNEL32.dll"),
        corrected_library: "KernelBase.dll",
    },
    LibraryOverride {
        symbol: "RestoreThreadPreferredUILanguages",
        sdk_library: Some("KERNEL32.dll"),
        corrected_library: "KernelBase.dll",
    },
    LibraryOverride {
        symbol: "SetThreadPreferredUILanguages2",
        sdk_library: Some("KERNEL32.dll"),
        corrected_library: "KernelBase.dll",
    },
    LibraryOverride {
        symbol: "InitializeXamlDiagnosticsEx",
        sdk_library: None,
        corrected_library: "Windows.UI.Xaml.dll",
    },
];
