[package]
name = "win32metadata-tools"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "win32metadata-tools"
path = "src/main.rs"

[dependencies]
windows-clang = { git = "https://github.com/jevansaks/windows-rs", rev = "2d6060c7d04136702374136abd690c0ad5e11449" }
windows-metadata = { git = "https://github.com/jevansaks/windows-rs", rev = "2d6060c7d04136702374136abd690c0ad5e11449" }
windows-rdl = { git = "https://github.com/jevansaks/windows-rs", rev = "2d6060c7d04136702374136abd690c0ad5e11449" }
