[package]
name = "win32metadata-tools"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "win32metadata-tools"
path = "src/main.rs"

[dependencies]
windows-clang = { git = "https://github.com/jevansaks/windows-rs", rev = "ea1f82785b2d84c5e1899c46efe9703a08f88e35" }
windows-metadata = { git = "https://github.com/jevansaks/windows-rs", rev = "ea1f82785b2d84c5e1899c46efe9703a08f88e35" }
windows-rdl = { git = "https://github.com/jevansaks/windows-rs", rev = "ea1f82785b2d84c5e1899c46efe9703a08f88e35" }
