[package]
name = "win32metadata-tools"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "win32metadata-tools"
path = "src/main.rs"

[dependencies]
windows-clang = { git = "https://github.com/jevansaks/windows-rs", rev = "181e339d72fc59e8ec30abec27bc41f07108ca11" }
windows-metadata = { git = "https://github.com/jevansaks/windows-rs", rev = "181e339d72fc59e8ec30abec27bc41f07108ca11" }
windows-rdl = { git = "https://github.com/jevansaks/windows-rs", rev = "181e339d72fc59e8ec30abec27bc41f07108ca11" }
